### ISSUE TITLE
inputTime error

### ISSUE THREAD

**Issue by jdnichollsc** [rajeshwarpatlolla/ionic-timepicker#82]
Hi man,

See an error using **inputTime**: http://screencast.com/t/kkB7tdkO0

I'm getting the inputTime with the code of the example:

```
inputTime : (($scope.myDate.getHours() * 60 * 60) + ($scope.myDate.getMinutes() * 60))
```

Regards, Nicholls

**Comment by jdnichollsc** [comment]
Fixed with the ticket #72

**Comment by Alphatiger** [comment]
Is this updated in the dist copy as well, we are using bower version and it still shows this bug, Any clues?

**Comment by jdnichollsc** [comment]
@philonor check please
